In [1]:
import numpy as np
np.__version__

'1.24.2'

## İndeksleme
- Basit indeksleme
    

In [2]:
arr = np.arange(1,11) # basit bir boyutlu array oluşturduk.
arr

# NOT : İndekslemede 0. indisi olarak çağırdığımızda ilk elaman gelecektir yani elemanlar indekslerden çağırıldığında 0. indis = 1. elemandır 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1] # 0. indisten başladığı için 1.indis = 2. eleman 

2

In [4]:
arr[2:6] # ": ' nın anlamı "dan sonra " demektir." , yani 2. indisten 6. indise kadar ama 6 dahil değildir.

array([3, 4, 5, 6])

In [5]:
arr[-3] # sondan olan indisleri de çağırabilirz. (-1 den başlar).

8

2d (iki boyutlu) indeksleme

In [6]:
arr1 = np.random.randn(3,3)
arr1 = arr1.round(decimals=1) # virgülden sonrasını kısalttık
arr1

array([[-0.9, -2.8, -0.8],
       [ 1.9,  1.3, -0.8],
       [ 0.3,  2.1, -0.3]])

In [7]:
arr1[0:1,2] # [0:2 , 2] virgül'ün sol tarafı satırları sağ tarafı ise sütunları çeker.

array([-0.8])

In [8]:
# -0.4 ile 0.2 ' yi çekmek için :

arr1[0:2 , 1] 

array([-2.8,  1.3])

## İleri Seviye İndeksleme : 

In [9]:
arr2 = np.random.randn(3,3)
arr2 = arr1.round(decimals=1) # virgülden sonrasını kısalttık
arr2

array([[-0.9, -2.8, -0.8],
       [ 1.9,  1.3, -0.8],
       [ 0.3,  2.1, -0.3]])

In [10]:
# -0.1 ile -0.2 ' yi çekme için:

arr2[[1 , -1] , [0 , 2]] 

array([ 1.9, -0.3])

# Boolean İndeksleme :

In [11]:
arr = np.array([i for i in range(50)]).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [12]:
# Tek olan sayıları bulmak: (uzun yoldur.)

for x in arr :
    for x_sub in x :
        if x_sub % 2 == 1 :
            print(x_sub)
       

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


In [13]:
arr[arr % 2 == 1] # kolay yöntemdir 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

## np.where() ve boolean indeksleme 
- np.where() ilk seferde indisleri döndürür 


In [16]:
arr = (np.random.rand(5,2) * 100).astype(int)
arr

array([[ 0, 56],
       [93, 46],
       [94, 26],
       [50, 57],
       [16, 83]])

In [19]:
arr[arr % 2 == 0] # boolean indeklemede yaptığımız gibi yaptık 

array([ 0, 56, 46, 94, 26, 50, 16])

np.where nerede kullanılır :
- indeklerini belirlemede kullanılır
- değiştirmek istediğiniz değerler

In [20]:
# np.where komutu ile yapımı 

arr[np.where(arr % 2 == 0)] 

array([ 0, 56, 46, 94, 26, 50, 16])

In [21]:
arr 

array([[ 0, 56],
       [93, 46],
       [94, 26],
       [50, 57],
       [16, 83]])

In [25]:
np.where(arr > 50 , 1 , 0) 
# değiştirmek için açıklaması şu şekilde : çıktılardaki sayılar 50 den büyükse bir yap değilse 0 yap.

array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1]])