In [31]:
import numpy as np 
np.__version__

'1.24.2'

## Broadcasting'e Giriş
- Denk gelen bütün indisleri kolayca dört işlemi olarak düşünülebilir.
    - Shapeleri aynı değilse devreye giren bir işlemdir

In [32]:
arr = np.array([1,2,3]) # shape'i (3,)

arr1 = np.array([[4,5,6] , [7,8,9]])  #shape' i (2,3)

arr , arr1

# iki farklı array oluşturduk şimdi bunlara broadcasting yapalım;

(array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [33]:
arr + arr1 # denk gelen indisleri topladık bu bie broadcasting olayıdır.

array([[ 5,  7,  9],
       [ 8, 10, 12]])

## İleri Seviye Broadcasting :

In [34]:
score = np.random.uniform(0,101, size = (20,4))
score.astype(np.int32)

array([[ 49,  37,  18,  89],
       [ 83,  51,  91,  17],
       [ 88,   0,  84,  41],
       [ 63,  45,  53,  57],
       [ 11,  75,  48,   7],
       [ 42,  87,  85, 100],
       [ 37,  49,  52,  21],
       [  5,   4,  84,  84],
       [ 35,  51,  76,   9],
       [ 76,  95,  24,  59],
       [  5,  32,  88,  29],
       [ 80,  21,  40,  95],
       [ 60,  36,   2,  29],
       [ 68,  76,  32,  98],
       [ 24,  67,  64,  60],
       [ 73,  44,  91,  86],
       [ 51,  87,  99,  68],
       [ 49,  31,  58,  74],
       [ 78,  32,  79,  40],
       [ 47,  69,   3,  63]])

In [35]:
# Satır bazlı ve sütun bazlı ortalamalarını bulalım :

score.mean(axis=1) # sütun bazlı ve shape'(20,) olacaktır.

array([48.65167194, 60.87687339, 53.87364404, 55.0330577 , 36.03832957,
       79.09245633, 40.04001293, 44.59080956, 43.08320473, 64.18423957,
       38.96549889, 59.35683967, 32.37687931, 69.26588265, 54.22467724,
       74.05767095, 76.70781628, 53.27562178, 57.63341136, 46.18923215])

In [36]:
# Satır bazlı olarak axis = 0 olması gerekmektedir:

score.mean(axis=0) # shape'i (4,) olacaktır

array([51.71824026, 50.01726995, 58.9947853 , 56.77327049])

# Array Birleştirme :
- np.concatenate ve np.stack komutları 

In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [38]:
np.concatenate([arr1 , arr2] , axis = 0)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.stack([arr1 , arr2] , axis = 0) # 2D oldu dikkat edelim.

array([[1, 2, 3],
       [4, 5, 6]])

2D array birleştirme :


In [40]:
arr3 = np.random.randint(low = 0 , high=5 , size = (4,4))
arr4 = np.random.randint(low = 0 , high=5 , size = (4,4))

arr3 , arr4

(array([[3, 1, 3, 0],
        [2, 4, 0, 1],
        [2, 4, 4, 4],
        [2, 2, 2, 0]]),
 array([[1, 4, 2, 0],
        [4, 1, 3, 1],
        [0, 4, 0, 1],
        [2, 4, 2, 3]]))

In [41]:
np.concatenate([arr3,arr4] , axis = 0) # arr3 ün bitiminde hemen altına arr4 arrayını ekledi. Shape = (8,4)

array([[3, 1, 3, 0],
       [2, 4, 0, 1],
       [2, 4, 4, 4],
       [2, 2, 2, 0],
       [1, 4, 2, 0],
       [4, 1, 3, 1],
       [0, 4, 0, 1],
       [2, 4, 2, 3]])

In [42]:
np.concatenate([arr3,arr4] , axis = 1) # arr3'ün bitiminde bu sefer yanına sağ tarafına ekledi yani sütun bazlı birleştirme yaptık. Shape = (4,8)

array([[3, 1, 3, 0, 1, 4, 2, 0],
       [2, 4, 0, 1, 4, 1, 3, 1],
       [2, 4, 4, 4, 0, 4, 0, 1],
       [2, 2, 2, 0, 2, 4, 2, 3]])

In [43]:
np.stack([arr3,arr4] , axis = 0) # bir bölme ile arrayi bozmadan satır bazlı birleştirme yaptık. 3D olduğuna dikkat edelim. Shape = (2,4,4)


array([[[3, 1, 3, 0],
        [2, 4, 0, 1],
        [2, 4, 4, 4],
        [2, 2, 2, 0]],

       [[1, 4, 2, 0],
        [4, 1, 3, 1],
        [0, 4, 0, 1],
        [2, 4, 2, 3]]])

In [44]:
a = np.stack([arr3,arr4] , axis = 1) # yukarıdaki arraya bakıp inceleybilirsiniz. Shape = (4,2,4)
a

array([[[3, 1, 3, 0],
        [1, 4, 2, 0]],

       [[2, 4, 0, 1],
        [4, 1, 3, 1]],

       [[2, 4, 4, 4],
        [0, 4, 0, 1]],

       [[2, 2, 2, 0],
        [2, 4, 2, 3]]])

## Structured Arrayler

In [54]:
st = np.array([("Metehan" , 100 , 60) , ("Emre" , 80 , 95)] , 
         dtype= [("ad" , "U10") , ("Ilk_Sınav" , "i4" ) , ("Ikıncı_Sınav" , "i4")])

st

array([('Metehan', 100, 60), ('Emre',  80, 95)],
      dtype=[('ad', '<U10'), ('Ilk_Sınav', '<i4'), ('Ikıncı_Sınav', '<i4')])

In [55]:
st[0] # İlk indeksi çağırdık.

('Metehan', 100, 60)

In [58]:
print(st["ad"] )

st["Ilk_Sınav"]

['Metehan' 'Emre']


array([100,  80])